### ISSUE TITLE
换个地方聊天..

### ISSUE THREAD

**Issue by KeJunMao** [ashidamana/ashidamana.github.io#1]
你的站炸了。。

编辑：`Status Code:449 `

友链信息按这个格式给我下：
```yaml
昵称：KeJun
网址：https://kejun.me
头像url：https://ooo.0o0.ooo/2017/03/14/58c775b701fd8.png
网站简介： 二次元智障
```

这也是我的友链信息

**Comment by ashidamana** [comment]
@KeJunMao 你再访问看看，我修复了，服务器故障。https://blog.mana.love/

你网站已经加在我的友链里了。
我的友链信息：
昵称：爱菜家希望之神小飞鸟
网址：https://blog.mana.love
头像url：https://ooo.0o0.ooo/2017/06/27/5951c38b7699a.jpg
网站简介：爱菜、爱菜、爱菜

**Comment by KeJunMao** [comment]
@ashidamana  好 ~    马上加~

加到这里啦~

https://blog.kejun.space/pages/friends.html

**Comment by ashidamana** [comment]
@KeJunMao 、看到啦，你的加在这里了https://blog.mana.love/links/
